export const projects = [
  {
    title: 'Sistem Informasi Konsultasi dan Pengawasan Inspektorat Jenderal Kemendikbud',
    description: "Develop a web based application for internal auditors to help them queries or find information and knowledge about some topics such as Investigations, Auditing, etc. Similar to stack overflow, only this one is intended to help internal auditors gain more insight that related to their field and jobs.",
      image: '/images/kbs.png',
      tags: ['Codeigniter', 'Bootstrap', 'MySQL'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Portal Perpustakaan Komnas HAM',
    description: "Develop a web based portal that linked to existing library system and add news feature. Develop a web based system to manage documentation of Komnas HAM in several formats, such as photos, videos and electronic documents",
      image: '/images/komnasham.png',
      tags: ['Codeigniter', 'Bootstrap', 'MySQL'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'AstraWorld SMS Gateway',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/webdev.png',
      tags: ['React', 'Redux', 'Sprint Boot', 'SQL Server'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'User Management',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/webdev.png',
    tags: ['Angular', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Sistem Pemanfaatan Dana',
    description: "The system involve end to end process of filtering eligible participants, managing huge number of parameters and master data, ensure the established scenario is able to filter and manage the participants data",
      image: '/images/pmf.png',
      tags: ['React', 'Nextjs', 'Redux Saga', 'Micro Front End', 'Material UI'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Sistem Pemupukan Dana',
    description: "System to manage the administration of Tapera's investment, displaying current portofolio and conduct fund approval.",
    image: '/images/pmp.png',
    tags: ['React', 'Nextjs', 'Redux Saga', 'Micro Front End', 'Material UI'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'STAR Astra Motor - Finance Module',
    description: "Develop a web based system, specifically in Financial Module that includes several menus such as incoming payment flow, outgoing payment flow, monitoring of incoming, monitoring of outgoing and monitoring general ledger. Coordinates the developers, assist and overcome any obstacles related to technical or non-technical. Coordinates with other squad for any dependant backlogs.",
    image: '/images/star-finance.png',
    tags: ['React', 'GraphQL', 'AntDesign', 'urlql'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Develop web based knowlegde base system in Itjen Kemendikbud and Library Portal in Komnas HAM', },
  { year: 2018, text: 'Develop SMS Gateway system in AstraWorld', },
  { year: 2019, text: 'Develop User Management in United Tractors', },
  { year: 2020, text: 'Develop User Sistem Pemanfaatan Dana & Sistem Pemupukan Dana in BP Tapera', },
  { year: 2022, text: 'Develop Finance Module in STAR Project Astra Internatonal', },
  { year: 2022, text: 'Scrum Master for Nahtuh', },
];